#!/usr/bin/env bash

# sea
# utility helper for launching various sea tools

CURRENT_DIR=$(dirname "$(readlink -f "$0")")

launch_util() {
    [[ ! -f "${CURRENT_DIR}/${1}/launch.sh" ]] && {
        echo "Error: Script ${CURRENT_DIR}/${1}/launch.sh does not exist"
        exit 1
    }

    bash "${CURRENT_DIR}/${1}/launch.sh" "${@:3}" & disown
}

util_handler() {
    # launch if no other args are given
    [[ -z "$2" ]] && launch_util "$1"
}

install() {
    local target_path="/usr/local/bin/sea"
    local script_path=$(readlink -f "$0")

    if [[ -f "$target_path" ]]; then
        echo "Error: $target_path already exists."

        echo -n "Remove and install it ? (y/n) "
        read -r answer
        if [[ "$answer" != "y" ]]; then
            echo "Installation aborted."
            exit 1
        fi

        sudo rm -f "$target_path" || {
            echo "Error: Unable to remove existing $target_path"
            exit 1
        }
    fi

    sudo ln -s "$script_path" "$target_path" || {
        echo "Error: Unable to copy script to $target_path"
        exit 1
    }

    sudo chmod +x "$target_path" || {
        echo "Error: Unable to make $target_path executable"
        exit 1
    }

    echo "sea utility installed successfully at $target_path"
}

show_help() {
    echo "Usage: sea [command] [args]"
    echo "Commands:"
    echo "  kill <process_name>   - Kill a specific sea process"
    echo "  killall               - Kill all sea processes"
    echo "  install               - Install the sea utility"
    echo "  <util_name> [args]   - Launch a specific sea utility"
    exit 0
}

remove() {
    local target_path="/usr/local/bin/sea"

    if [[ -f "$target_path" ]]; then
        sudo rm -f "$target_path" || {
            echo "Error: Unable to remove $target_path"
            exit 1
        }
        echo "sea utility removed successfully from $target_path"
    else
        echo "Error: $target_path does not exist."
        exit 1
    fi
}

case "$1" in
    kill)
        pkill -f "$2" || {
            echo "Error: Unable to kill sea processes"
            exit 1
        }
    ;;
    killall)
        pkill -f "sea" || {
            echo "Error: Unable to kill all sea processes"
            exit 1
        }
    ;;
    install)
        install "$0"
    ;;
    remove)
        remove
    ;;
    help|--help|-h)
        show_help
    ;;
    *)
        [[ -z "$1" ]] && show_help
        util_handler ${@}
    ;;
esac
